# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=50)),
                ('Facebook_Profile_Link', models.URLField()),
                ('Github_Profile_Link', models.URLField(blank=True, null=True)),
                ('Linkedin_Profile_Link', models.URLField(blank=True, null=True)),
                ('Image', models.ImageField(height_field='height_field', upload_to='', width_field='width_field')),
                ('Key', models.CharField(max_length=100)),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='added_by',
            new_name='team_name',
        ),
        migrations.AddField(
            model_name='information',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='information',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
