# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_list_of_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='Github_Profile_Link',
            field=models.URLField(),
        ),
    ]
